'use client'
import './globals.css'
import React, {useEffect} from 'react';

// const inter = Inter({subsets: ['latin']})
//
// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({children}) {

    useEffect(() => {
        const setThemeFromCookie = () => {
            const themeState = document.getElementById('content');
            themeState.className = isThemeSelected() ? 'light-mode' : 'dark-mode';
        };

        const isThemeSelected = () => {
            return document.cookie.match(/theme=dark/i) != null;
        };

        const toggleTheme = () => {
            const themeState = document.getElementById('content');
            const newState = themeState.className === 'dark-mode' ? 'light-mode' : 'dark-mode';
            themeState.className = newState;
            document.cookie = 'theme=' + (newState === 'light-mode' ? 'light' : 'dark') + '; path=/';
        };

        setThemeFromCookie();
        const toggleElement = document.getElementById('toggleTheme');
        if (toggleElement) {
            toggleElement.onchange = toggleTheme;
        }
    }, []);

    const toggleMenu = () => {
        const menu = document.querySelector('.mobile_menu');
        menu.classList.toggle('visible');
    };


    return (
        <html lang="en">
        <body cz-shortcut-listen="true">

        {children}

        </body>
        </html>
    )
}
